### ISSUE TITLE
Andriod Build 4.27 Unreal Issue with armv7

### ISSUE THREAD

**Issue by ssshammi** [shanecolb/sphinx-ue4#22]
@hgamiel @shanecolb HI I mange to fix a few bugs and make it work with UE 4.27 and package as windows, however i am not able to package as andriod 

![image](https://user-images.githubusercontent.com/2300969/178085686-a80c8a95-b805-494d-a029-c7ce888903a1.png)
`UATHelper: Packaging (Android (ASTC)):     In file included from D:/Others/Sppechtest/Plugins/SpeechRecognition/Source/SpeechRecognition/Public\SpeechRecognitionSubsystem.h:6:
UATHelper: Packaging (Android (ASTC)):     D:/Others/Sppechtest/Plugins/SpeechRecognition/Source/SpeechRecognition/Public/SpeechRecognitionWorker.h(4,10): fatal error: 'sphinxbase/ad.h' file not found
UATHelper: Packaging (Android (ASTC)):     #include <sphinxbase/ad.h>
UATHelper: Packaging (Android (ASTC)):              ^~~~~~~~~~~~~~~~~
UATHelper: Packaging (Android (ASTC)):     1 error generated.
PackagingResults: Error: 'sphinxbase/ad.h' file not found`

Issue with SpeechRecognitionWorker.h file. how I think you guys were able to port it to andriod. can you tell me what do i need to change for it to load it for andriod?
![image](https://user-images.githubusercontent.com/2300969/178085718-148d76cb-37c3-48d5-a9a1-f2dea03bcb6c.png)

**Comment by ssshammi** [comment]
I am guessing i just need to add something in SpeechRecognition.Build.cs for armv7 ?
