### ISSUE TITLE
Ue4 24.4 engine use packaging problem 

### ISSUE THREAD

**Issue by amatasora** [shanecolb/sphinx-ue4#19]
hey in ue 24.2 it works still good in the engine but when time comes to package it I get a error saying D:\MyProject\Plugins\SpeechRecognition\Source\SpeechRecognition\Private\SpeechRecognitionActor.cpp(1): error: Expected SpeechRecognitionActor.h to be first header included.

**Comment by gillj007** [comment]
Hi do you mind to tell me how to make it work in 24.2?

Thanks

**Comment by NextWorldVR** [comment]
> hey in ue 24.2 it works still good in the engine but when time comes to package it I get a error saying D:\MyProject\Plugins\SpeechRecognition\Source\SpeechRecognition\Private\SpeechRecognitionActor.cpp(1): error: Expected SpeechRecognitionActor.h to be first header included.

ANY CHANCE YOU MIGHT EVER ANSWER THIS PERSON ABOVE?
